[package]
name = "ledger"
version = "0.2.5"
authors = ["ZondaX GmbH <info@zondax.ch>"]
description = "Library to exchange APDU with Ledger Nano S devices"
homepage = "https://github.com/zondax/ledger-rs"
repository = "https://github.com/zondax/ledger-rs"
readme = "README.md"

license = "Apache-2.0"
keywords = ["ledger", "nano", "blue", "apdu"]

[lib]
name = "ledger"

[dependencies]
byteorder = "1.2.4"
libc = "0.2.50"
quick-error = "1.2.2"
cfg-if = "0.1.7"
lazy_static = "1.3.0"
hex = "0.3.2"

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.13.0"

[dependencies.hidapi]
version = "=0.5.2"
default-features = false
